/**
 * Graph List Types
 *
 * Type definitions for the persistent graph working set feature.
 * The graph list stores currently visible nodes in the graph visualization
 * and bypasses entity type filters (solving the "invisible expansion" bug).
 */

import type { EntityType } from "../entities/entities.js";

/**
 * Provenance tracking for graph list nodes
 * Indicates how a node was added to the graph list
 */
export type GraphProvenance =
  | "user" // Explicitly added by user via search/UI
  | "collection-load" // Added when loading from bookmarks/history
  | "expansion" // Added when user expands node relationships
  | "auto-population"; // Added by background auto-population system

/**
 * Node in the persistent graph working set
 *
 * Stored in IndexedDB via CatalogueStorageProvider interface.
 * Bypasses entity type filters (always visible when in graph list).
 */
export interface GraphListNode {
  /**
   * Unique identifier (auto-generated by storage provider)
   * Format: UUID v4 or similar
   */
  id: string;

  /**
   * OpenAlex entity ID
   * @example "W2741809807" (work), "A5017898742" (author)
   */
  entityId: string;

  /**
   * Entity type from OpenAlex
   * @example "works", "authors", "institutions", "sources", "topics"
   */
  entityType: EntityType;

  /**
   * Display label for the node
   * Extracted from entity data (e.g., work title, author name)
   */
  label: string;

  /**
   * Timestamp when node was added to graph list
   * Used for pruning old auto-populated nodes
   */
  addedAt: Date;

  /**
   * How this node was added to the graph list
   * Used for UI display and pruning strategy
   */
  provenance: GraphProvenance;
}

/**
 * Parameters for adding a node to the graph list
 */
export interface AddToGraphListParams {
  entityId: string;
  entityType: EntityType;
  label: string;
  provenance: GraphProvenance;
}

/**
 * Result of prune operation
 */
export interface PruneGraphListResult {
  /**
  Number of nodes removed
   */
  removedCount: number;
  /**
  IDs of nodes that were removed
   */
  removedNodeIds: string[];
}

/**
 * Graph list configuration constants
 * Extracted to prevent magic numbers (Constitution Principle XVII)
 */
export const GRAPH_LIST_CONFIG = {
  /**
  Maximum number of nodes allowed in graph list
   */
  MAX_SIZE: 1000,

  /**
  Threshold for showing "approaching limit" warning
   */
  WARNING_THRESHOLD: 900,

  /**
  Age threshold for pruning auto-populated nodes (milliseconds)
   */
  PRUNE_AGE_MS: 24 * 60 * 60 * 1000, // 24 hours

  /**
  Special list ID for graph list in storage
   */
  LIST_ID: "graph-list",
} as const;
